CoreDemo/Models/ErrorViewModel.cs
using System;

namespace CoreDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreDemo/Models/UserComment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Models
{
    public class UserComment
    {
        public int ID { get; set; }
        public string UserName { get; set; }

    }
}

CoreDemo/Models/WriterCity.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Models
{
    public class WriterCity
    {
        public List<SelectListItem> GetCityList()
        {
            String[] CitiesArray = { "Adana", "Adıyaman", "Afyon", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Bartın", "Batman", "Balıkesir", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "İçel", "İstanbul", "İzmir", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale", "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Şırnak", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" };
            new List<string>(CitiesArray);//arrayi liste çevirme

            List<SelectListItem> cities = (from x in CitiesArray
                                           select new SelectListItem
                                           {
                                               Text = x,
                                               Value = x
                                           }).ToList();


            List<SelectListItem> cities1 = new()
            {
             for (int i = 0; i < CitiesArray.Length; i++)
            {
                new SelectListItem { Value = i, Text = CitiesArray[i] }

            } };
            ViewBag
            return cities;

        }
    }

}

CoreDemo/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class BlogController : Controller
    {
        BlogManager bm = new BlogManager(new EfBlogRepositoy());
        public IActionResult Index()
        {
            var values = bm.GetBlogListWithCategory();
            return View(values);
        }

        public IActionResult BlogDetails(int id)
        {
            ViewBag.i = id;
            var values = bm.GetBlogById(id);
            return View(values);
        }
    }
}

CoreDemo/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Abstract;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryRepositoy());
        public IActionResult Index()
        {
            var values = categoryManager.GetAllList();
            return View(values);
        }
    }
}

CoreDemo/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class CommentController : Controller
    {
        CommentManager commentManager = new CommentManager(new EfCommentRepository());

        public PartialViewResult PartialAddComment()
        {
            return PartialView();
        }

        public PartialViewResult CommentListByBlog(int id)
        {
           var values= commentManager.GetAllList(id);
            return PartialView(values);
        }

    }
}

CoreDemo/Controllers/HomeController.cs
using CoreDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace CoreDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Test()
        {
            return View();
        }
    }
}

CoreDemo/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreDemo/Controllers/RegisterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class RegisterController : Controller
    {
        WriterManager _writerManager = new WriterManager(new EfWriterRepositoy());

        [HttpGet]// Sayfa yuklenince
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]// sayfadaki kaydet tetiklenince
        public IActionResult Index(Writer writer)
        {
            WriterValidator writerValidator = new WriterValidator();
            ValidationResult result = writerValidator.Validate(writer);
            if (result.IsValid)
            {
                writer.WirterStatus = true;
                writer.WriterAbout = "Deneme Test";
                _writerManager.WriterAdd(writer);
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }
    }
}

CoreDemo/Views/Blog/BlogDetails.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@{
    ViewData["Title"] = "BlogDetails";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<!--
    Author: W3layouts
    Author URL: http://w3layouts.com
    License: Creative Commons Attribution 3.0 Unported
    License URL: http://creativecommons.org/licenses/by/3.0/
-->

<!DOCTYPE html>
<html lang="zxx">
<body>
    <!--Header-->
    <!--//header-->
    <!--//banner-->
    <section class="banner-bottom">
        <!--/blog-->
        <div class="container">
            <div class="row">
                <!--left-->
                <div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
                    @foreach (var item in Model)
                    {
                        <div class="blog-grid-top">
                            <div class="b-grid-top">
                                <div class="blog_info_left_grid">
                                    <a href="single.html">
                                        <img src="@item.BlogImage" class="img-fluid" alt="">
                                    </a>
                                </div>
                                <div class="blog-info-middle">
                                    <ul>
                                        <li>
                                            <a href="#">
                                                <i class="far fa-calendar-alt"></i>@item.BlogCreateDate
                                            </a>
                                        </li>
                                        <li class="mx-2">
                                            <a href="#">
                                                <i class="far fa-thumbs-up"></i>0 Likes
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="far fa-comment"></i> 15 Comments
                                            </a>
                                        </li>

                                    </ul>
                                </div>
                            </div>

                            <h3>
                                <a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle </a>

                            </h3>
                            <p>
                                @item.BlogContent
                            </p>
                            <a href="/Blog/Index/" class="btn btn-primary read-m">Blog Listesi</a>
                        </div>

                    }
                    @await Component.InvokeAsync("CommentListByBlog",new {id=ViewBag.i })

                    @*@await Html.PartialAsync("~/Views/Comment/CommentListByBlog.cshtml")*@
                    @await Html.PartialAsync("~/Views/Comment/PartialAddComment.cshtml")

                </div>

                <!--//left-->
                <!--right-->
                <aside class="col-lg-4 agileits-w3ls-right-blog-con text-right">
                    <div class="right-blog-info text-left">
                        <div class="tech-btm">
                            <img src="~/CoreBlogTema/images/banner1.jpg" class="img-fluid" alt="">
                        </div>
                        <div class="tech-btm">
                            <h4>Sign up to our newsletter</h4>
                            <p>Pellentesque dui, non felis. Maecenas male </p>
                            <form action="#" method="post">
                                <input type="email" placeholder="Email" required="">
                                <input type="submit" value="Subscribe">
                            </form>

                        </div>
                        @await Component.InvokeAsync("CategoryList")
                       
                        @await Component.InvokeAsync("WriterLastBlogComponent")

                        <div class="single-gd my-5 tech-btm">
                            <h4>Our Progress</h4>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="single-gd tech-btm">
                            <h4>Son Yüklenen</h4>
                            <div class="blog-grids">
                                <div class="blog-grid-left">
                                    <a href="single.html">
                                        <img src="images/b1.jpg" class="img-fluid" alt="">
                                    </a>
                                </div>
                                <div class="blog-grid-right">

                                    <h5>
                                        <a href="single.html">Pellentesque dui, non felis. Maecenas male</a>
                                    </h5>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>

                </aside>
                <!--//right-->
            </div>
        </div>
    </section>



</body>

</html>

CoreDemo/Views/Blog/Index.cshtml
@using EntityLayer.Concrete
@model List<Blog>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Bloglar</h3>
        <div class="inner-sec">
            <!--left-->
            <div class="left-blog-info-w3layouts-agileits text-left">
                <div class="row">
                    @foreach (var item in Model)
                    {

                        <div class="col-lg-4 card">
                            <a href="single.html">
                                <img  src="@item.BlogImage" class="card-img-top img-fluid" alt="" style="width:400px ; height:400px" >
                            </a>
                            <div class="card-body">
                                <ul class="blog-icons my-4">
                                    <li>
                                        <a href="#">
                                            <i class="far fa-calendar-alt"></i>@item.BlogCreateDate
                                        </a>
                                    </li>
                                    <li class="mx-2">
                                        <a href="#">
                                            <i class="far fa-comment"></i>0
                                        </a>
                                    </li>
                                    <li>
                                         <a href="#">
                                            <i class="fas fa-eye"></i>@item.Category.CategoryName
                                        </a>
                                    </li>

                                </ul>
                                <h5 class="card-title">
                                    <a href="/Blog/BlogDetails/@item.BlogID">@item.BlogTitle
                                    </a>
                                </h5>
                                <p class="card-text mb-3">
                                    @(item.BlogContent.Length>50 ? item.BlogContent.Substring(0,item.BlogContent.Substring(0,55).LastIndexOf(" "))+"..." : item.BlogContent)
                                </p>
                                <a href="/Blog/BlogDetails/@item.BlogID" class="btn btn-primary read-m">Devamını Oku</a>
                                <br />
                                <br />
                            </div>
                        </div>
                    }

                </div>
                <!--//left-->
            </div>
        </div>
    </div>
</section>

CoreDemo/Views/Category/Index.cshtml
@using EntityLayer.Concrete;
@model List<Category>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kategoriler</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <table class="table table-bordered">
        <tr>
            <th scope="col">ID</th>
            <th>Kategori Adı</th>
            <th>Durumu</th>
            <th>Detaylar</th>
            <th>Sil</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.CategoryID</th>
                <td>@item.CategoryName</td>
                <td>@item.CategoryStatus</td>
                <td><a href="" class="btn btn-warning"></a>@item.CategoryDescription</td>
                <td><a class="btn btn-danger" href="">Sil</a></td>
            </tr>
        }
    </table>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</body>
</html>

CoreDemo/Views/Comment/CommentListByBlog.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>
<div class="comment-top">
    <h4>Yorumlar</h4>
    <div class="media">
        <img src="~/CoreBlogTema/images/t1.jpg" alt="" class="img-fluid" />
        <div class="media-body">
            <h5 class="mt-0">Joseph Goh</h5>
            <p>
                Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                Cras a ornare elit.
            </p>

            <div class="media mt-3">
                <a class="d-flex pr-3" href="#">
                    <img src="images/t2.jpg" alt="" class="img-fluid" />
                </a>
                <div class="media-body">
                    <h5 class="mt-0">Richard Spark</h5>
                    <p>
                        Lorem Ipsum convallis diam consequat magna vulputate malesuada. id dignissim sapien velit id felis ac cursus eros.
                        Cras a ornare elit.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

CoreDemo/Views/Comment/PartialAddComment.cshtml
<div class="comment-top">
    <h4>Yorum Yazın</h4>
    <div class="comment-bottom">
        <form action="#" method="post">
            <input class="form-control" type="text" name="Name" placeholder="Name" required="">
            <input class="form-control" type="email" name="Email" placeholder="Email" required="">

            <input class="form-control" type="text" name="Subject" placeholder="Subject" required="">

            <textarea class="form-control" name="Message" placeholder="Message..." required=""></textarea>
            <button type="submit" class="btn btn-primary submit">Submit</button>
        </form>
    </div>
</div>

CoreDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreDemo/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Oturum Açma</h3>
        <div class="row inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                <form action="#" method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1 mb-2">Email </label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
                        <small id="emailHelp" class="form-text text-muted">Mail adresi kimseyle paylaşılmaz.</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1 mb-2">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="" required="">
                    </div>
                    <div class="form-check mb-2">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1">Beni Hatırla</label>
                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Giris Yap</button>
                    <p><a href="/Register/Index/"> Bir hesabın yok mu?</a></p>
                </form>
            </div>
        </div>
    </div>
</section>

CoreDemo/Views/Register/Index.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Yazar Kayıt Sayfasi</h3>
        <div class="inner-sec">
            <div class="login p-5 bg-light mx-auto mw-100">
                @using (Html.BeginForm("Index", "Register", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom01">Adınız Soyadınız</label>

                            @*<input type="text" class="form-control" id="validationDefault01" name="WriterName"
                                placeholder="" required="">*@
                            @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="validationCustom02">Mail Adresiniz</label>
                            @*<input type="email" class="form-control" id="validationDefault02" name="WriterMail"
                                placeholder="" required="">*@
                            @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterMail, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword1 mb-2">Şifre</label>
                            @*<input type="password" class="form-control" id="password1" name="WriterPassword"
                                placeholder="" required="">*@
                            @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @class = "text-danger" })
                        </div>
                        @*<div class="form-group col-md-6">
                                <label for="exampleInputPassword2 mb-2">Confirm Password</label>
                                <input type="password" class="form-control" id="password2" placeholder="" required="">
                            </div>*@
                        @Html.Password("passwordAgain", "", new { @class = "form-control", @id = "password2", @placeholder = "Şifre Giriniz", @required = "" })
                        @Html.ValidationMessageFor(x => x.WriterPassword, "", new { @class = "text-danger" })


                        <div class="form-group col-md-6">
                            <label for="exampleInputPassword2 mb-2">Gorsel Dosya Yolu</label>
                            @*<input type="text" class="form-control" id="WriterImage" name="WriterImage"
                                placeholder="" required="">*@
                            @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.WriterImage, "", new { @class = "text-danger" })
                        </div>

                        @*<div class="form-group col-md-6">
                                <label for="validationCustom01 mb-2">Şehir</label>
                                @Html.DropDownListFor(x => x.WriterCity,(List<SelectListItem>)ViewBag, new { @class = "form-control dropdown" })
                            </div>*@

                    </div>
                    <button type="submit" class="btn btn-primary submit mb-4">Kayıt Ol</button>
                    <p>
                        <a href="#" id="btn1">Tüm şartları okudum,kabul ediyorum</a>
                    </p>
                }
            </div>
        </div>
    </div>

    <script>
        $('#btn1').click(function () {
            swal("Sitemize Kayıt Sözleşmesi", "Sitemizde verdiğiniz mail adresi uzerinden bilgi ve haber epostalari spam ölçüsüne varmadan gönderilmeye devam edecektir. İstemezseniz durdurabilirsiniz.Şifre ve mail adresiniz şifrelenmiş durumda herhangi bir kullnaci erişemeyecek şekilde kayıt edilmektedir");
        });
    </script>
</section>

CoreDemo/Views/Shared/Components/CommentList/Default.cshtml
<h1>burası view component</h1>

CoreDemo/Views/Shared/Components/CommentListByBlog/Default.cshtml
@model IEnumerable<EntityLayer.Concrete.Comment>
<div class="comment-top">
    <h4>Yorumlar</h4>
    @if (Model.Count() == 0)
    {
        <h5>İlk Yorumu Siz Yapın</h5>
        <marquee behavior=alternate> <font color="red">Hayde acele  et</font></marquee>
    }

    @foreach (var item in Model)
    {
        <div class="media">

            <img src="~/CoreBlogTema/images/t1.jpg" alt="" class="img-fluid" />
            <div class="media-body">
                <h5 class="mt-0">@item.CommentUserName</h5>
                <p>
                    @item.CommentContent
                </p>


            </div>
        </div>
    }
</div>

CoreDemo/Views/Shared/Components/WriterLastBlogComponent/Default.cshtml
@using EntityLayer.Concrete
@model List<Blog>

    <div class="tech-btm">
        <h4>Yazarın Diğer Yazıları</h4>

        @foreach(var item in Model){
        <div class="blog-grids row mb-3">
            <div class="col-md-5 blog-grid-left">
                <a href="single.html">
                    <img src="@item.BlogImage" class="img-fluid" alt="">
                </a>
            </div>
            <div class="col-md-7 blog-grid-right">

                <h5>
                    <a href="single.html">@item.BlogTitle </a>
                </h5>
                <div class="sub-meta">
                    <span>
                        <i class="far fa-clock"></i> @item.BlogCreateDate
                    </span>
                </div>
            </div>

        </div>
        }S
    </div>

CoreDemo/Views/Shared/Partial1.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.html">
                        AnaSayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html">Hakkımızda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">Bloglar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">İletişim</a>
                </li>

            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Aranacak kelime..." name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>

</div>

CoreDemo/Views/Shared/Partial2.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span>Hoşgeldiniz!</span>
    <span class="mx-lg-4 mx-md-2  mx-1">
        <a href="login.html">
            <i class="fas fa-lock"></i> Giriş Yap
        </a>
    </span>
    <span>
        <a href="~/Register/Index">
            <i class="far fa-user"></i> Kayıt Ol
        </a>
    </span>
</div>

CoreDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CoreDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>